attendance_book/urls.py
from django.urls import path

from . import views

app_name = 'attendance_book'

urlpatterns = [
    path('', views.index, name='index'),
    path('teacher/input/', views.teach_in, name='teacher-input'),
    path('teacher/aggregation/', views.teach_agg, name='teacher-aggregation'),
    path('student/', views.student, name='student'),
    path('teacher/input/post/', views.teach_in_post, name='teacher-input-post'),
    path('teacher/aggregation/post/', views.teach_agg_post, name='teacher-aggregation-post'),
    path('teacher/aggregation/download/', views.teach_agg_download, name='teacher-aggregation-download'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('attendance_book/', include('attendance_book.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/attendance_book/')),
]

attendance_book/models.py
from django.db import models

from django.db import models


class Person(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    def __str__(self):
        return self.name


class Subject(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name


class Student(models.Model):
    student_num = models.CharField(max_length=6, primary_key=True)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    class_num = models.IntegerField()
    def __str__(self):
        return str(self.class_num) + " " + self.person.name

class Teacher(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    def __str__(self):
        return self.person.name


class Timetable(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    day_of_week = models.IntegerField()
    start_period = models.IntegerField()
    period_length = models.IntegerField()
    def __str__(self):
        return str(self.day_of_week) + " " + self.subject.name + " " + self.teacher.person.name

class Attendance(models.Model):
    date = models.DateField()
    period = models.IntegerField()
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    status = models.IntegerField()
    def __str__(self):
        return str(self.date) + " " + self.student.person.name + " " + self.subject.name + " " + str(self.status)

attendance_book/views.py
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse
from django.db.models import Q

from .models import Attendance, Student, Subject, Timetable, Teacher

import datetime
from urllib.parse import urlencode, quote
import json
import csv

def index(request):
    return render(request, 'attendance_book/index.html')

def teach_in(request):
    date = timezone.now().date()
    
    if "d" in request.GET:
        date_string = request.GET["d"]
        date = datetime.datetime.strptime(date_string, "%Y-%m-%d").date()
    
    attendance = Attendance.objects.filter(date=date).order_by("period")
    student = Student.objects.all().order_by("class_num")
    teacher = Teacher.objects.all()
    subject = Subject.objects.all()

    attendance_status = {}
    for s in student:
        attendance_status[s.student_num] = {}
        for at in attendance.filter(student=s):
            attendance_status[s.student_num][at.period] = at.status
    
    timetable = attendance.values("subject", "period").distinct()
    timetable_dict = {}
    sbj_id = -1
    start_period = -1
    period_length = 0
    for tt in timetable:
        if tt["subject"] == sbj_id and tt["period"] == start_period + period_length:
            timetable_dict[start_period]["period_length"] += 1
            period_length += 1
        else:
            sbj_id = tt["subject"]
            start_period = tt["period"]
            period_length = 1
            timetable_dict[start_period] = {}
            timetable_dict[start_period]["period_length"] = 1
            timetable_dict[start_period]["subject"] = Subject.objects.get(pk=sbj_id).name

    context = {
        "d": date,
        "student_list": student,
        "timetable": json.dumps(timetable_dict),
        "attendance_status": json.dumps(attendance_status),
        "teacher_list": teacher,
        "subject_list": subject,
    }
    
    return render(request, 'attendance_book/teach_in.html', context)

def teach_in_post(request):
    if "search-date" in request.POST:
        #print("search-date", request.POST)
        date_string = request.POST["date"]
        url = reverse('attendance_book:teacher-input')
        param = urlencode({"d": date_string})
        return HttpResponseRedirect(f"{url}?{param}")
        
    elif "create-timetable" in request.POST:
        #print("create-timetable", request.POST)
        date_string = request.POST["date"]
        url = reverse('attendance_book:teacher-input')
        param = urlencode({"d": date_string})
        date = datetime.datetime.strptime(date_string, "%Y-%m-%d").date()
        if Attendance.objects.filter(date=date):
            #エラー：既にデータが存在している
            print("error")
            return HttpResponseRedirect(f"{url}?{param}")
        week = date.weekday()
        timetable = Timetable.objects.filter(day_of_week=week)
        student = Student.objects.all().order_by("class_num")
        at_obj_list = []
        for tt in timetable:
            sp = tt.start_period
            pl = tt.period_length
            for s in student:
                for i in range(pl):
                    at_obj_list.append(Attendance(date=date, period=sp+i, student=s, teacher=tt.teacher, subject=tt.subject, status=0))
        Attendance.objects.bulk_create(at_obj_list)
        return HttpResponseRedirect(f"{url}?{param}")

    elif "update-status" in request.POST:
        date_string = request.POST["date"]
        date = datetime.datetime.strptime(date_string, "%Y-%m-%d").date()
        attendance = Attendance.objects.filter(date=date)
        student = Student.objects.all()
        at_obj_list = []
        for key in request.POST:
            if key[:7] == "status-":
                status = int(request.POST[key])
                student_num = key[7:13]
                period = int(key[14])
                s = student.get(pk=student_num)
                at = attendance.get(student=s, period=period)
                if at.status != status:
                    at.status = status
                    at_obj_list.append(at)
        Attendance.objects.bulk_update(at_obj_list, ["status"])
        url = reverse('attendance_book:teacher-input')
        param = urlencode({"d": date_string})
        return HttpResponseRedirect(f"{url}?{param}")
   
    elif "delete-sub" in request.POST:
        #print(request.POST)
        date_string = request.POST["date"]
        date = datetime.datetime.strptime(date_string, "%Y-%m-%d").date()
        dbutton = int(request.POST["num_button"])
        dbutton_len = int(request.POST["num_button_len"])
        try:
            q = Q()
            for i in range(dbutton_len):
                q |= Q(period=dbutton+i)
            Attendance.objects.filter(Q(date=date) & q).delete()
        except:
            print("Not Found Date")
        url = reverse('attendance_book:teacher-input')
        param = urlencode({"d": date_string})
        return HttpResponseRedirect(f"{url}?{param}")

    elif "create-sub" in request.POST:
        sp = int(request.POST["create-sub-sp"])
        pl = int(request.POST["create-sub-pl"])
        t_id = request.POST["create-sub-teacher"]
        s_id = request.POST["create-sub-subject"]
        date_string = request.POST["date"]
        date = datetime.datetime.strptime(date_string, "%Y-%m-%d").date()

        student = Student.objects.all().order_by("class_num")
        teacher = Teacher.objects.get(pk=t_id)
        subject = Subject.objects.get(pk=s_id)

        at_obj_list = []

        for s in student:
            for i in range(pl):
                at_obj_list.append(Attendance(date=date, period=sp+i, student=s, teacher=teacher, subject=subject, status=0))
        Attendance.objects.bulk_create(at_obj_list)

        url = reverse('attendance_book:teacher-input')
        param = urlencode({"d": date_string})
        return HttpResponseRedirect(f"{url}?{param}")
        
    #print(request.POST)
    # 404 not found
    return HttpResponseRedirect(reverse('attendance_book:teacher-input'))

def teach_agg(request):
    from_date = timezone.now().date()
    to_date = timezone.now().date()
    subject = None
    msg = ""
    istotal = False

    if "from_d" in request.GET:
        from_date_string = request.GET["from_d"]
        from_date = datetime.datetime.strptime(from_date_string, "%Y-%m-%d").date()
    if "to_d" in request.GET:
        to_date_string = request.GET["to_d"]
        to_date = datetime.datetime.strptime(to_date_string, "%Y-%m-%d").date()
    if "sbj" in request.GET:
        subject_pk = request.GET["sbj"]

        if subject_pk == "0":
            istotal = True
        else:
            try:
                subject = Subject.objects.get(pk=subject_pk)
            except Subject.DoesNotExist:
                subject = None
                msg = "That subject dose not exist."

    student = Student.objects.all().order_by("class_num")
    subject_list = Subject.objects.all().order_by("pk")

    if istotal:
        attendance = Attendance.objects.filter(date__gte=from_date, date__lte=to_date)
        date_list = attendance.values("date").distinct()

        attendance_count = {}
        for s in student:
            attendance_count[s.student_num] = {"days_class": 0, "days_absence": 0, "days_late": 0, "days_early": 0}
            at = attendance.filter(student=s)
            for d in date_list:
                a = at.filter(date=d["date"]).order_by("period")

                total_cnt = a.count()
                natd_cnt = a.filter(status=1).count()
                islate = False
                isearly = False
                if a.first().status == 1:
                    for i in a:
                        if i.status == 0:
                            islate = True
                            break
                if a.last().status == 1:
                    for i in a.reverse():
                        if i.status == 0:
                            isearly = True
                            break

                attendance_count[s.student_num]["days_class"] += 1
                attendance_count[s.student_num]["days_absence"] += 1 if natd_cnt == total_cnt else 0
                attendance_count[s.student_num]["days_late"] += 1 if islate else 0
                attendance_count[s.student_num]["days_early"] += 1 if isearly else 0
            attendance_count[s.student_num]["num_class"] = at.exclude(subject=1).count()
            attendance_count[s.student_num]["num_absence"] = at.exclude(subject=1).filter(status=1).count()

        context = {
            "from_d": from_date,
            "to_d": to_date,
            "student_list": student,
            "subject_list": subject_list,
            "attendance_count": json.dumps(attendance_count),
            "msg": msg
        }
        return render(request, 'attendance_book/teach_agg_total.html', context)

    else:
        attendance = Attendance.objects.filter(date__gte=from_date, date__lte=to_date, subject=subject)
        date_list = attendance.values("date").distinct()

        attendance_count = {}
        for s in student:
            attendance_count[s.student_num] = {"days_class": 0, "days_absence": 0, "days_late": 0, "days_early": 0}
            at = attendance.filter(student=s)
            for d in date_list:
                a = at.filter(date=d["date"]).order_by("period")

                total_cnt = a.count()
                natd_cnt = a.filter(status=1).count()
                islate = False
                isearly = False
                if a.first().status == 1:
                    for i in a:
                        if i.status == 0:
                            islate = True
                            break
                if a.last().status == 1:
                    for i in a.reverse():
                        if i.status == 0:
                            isearly = True
                            break

attendance_book/templates/attendance_book/akamatsu.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>TEST</title>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
            integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
            crossorigin="anonymous">
    </script>

    <style>

button {
  -moz-appearance: none;
  -webkit-appearance: none;

  margin: 1em 0; /* 前後の隙間 */
  padding: 0.6em 1em; /* 塗りの余白 */
  font-size: 1em; /* フォントサイズ */
  background-color: #e0ffff; /* 背景色 */
  color: #000; /* テキストカラー */
  cursor: pointer; /* カーソルを指マークに */
  border-radius: 3px; /* 角の丸み */
  border: 1px solid #000; /*グリッド*/
  transition: 0.3s; /* ホバーの変化を滑らかに */
}

/* ホバー時（カーソルをのせた時）の見た目 */
        button:hover {
            background-color: #0ff; /* 背景色 */
        }

.dropbtn {
    background-color: #e0ffff;
    color: black;
    padding: 0.6em 1em;
    font-size: 1em;
    border-radius: 3px;
    border: 1px solid #000;
    transition: 0.3s;
    cursor: pointer;
}

.dropdown {
    position: relative;
    display: inline-block;
}

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #e0ffff;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        }

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

.dropdown-content a:hover {background-color: #0ff}

.dropdown:hover .dropdown-content {
    display: block;
}

.dropdown:hover .dropbtn {
    background-color: #0ff;
}



    </style>

    <script>
        $(function(){
        $('.btn').on('click', function(event){
        event.preventDefault();
        $(this).toggleClass('active');
        });
        });
        $(function(){
        $('.btn2').on('click', function(event){
        event.preventDefault();
        $(this).toggleClass('active');
        });
        });
    </script>

</head>
<body>
    <button type="button">入力</button>
    <button type="button">集計</button>
    <div class="dropdown">
        <button class="dropbtn"> 科目 </button>
        <div class="dropdown-content">
            <a href="#"> 科目 1 </a>
            <a href="#"> 科目 2 </a>
            <a href="#"> 科目 3 </a>
        </div>
    </div>
    <button type="button">出力(CSV形式)</button>
</html>

attendance_book/templates/attendance_book/begin.html
<!DOCTYPE html>
<html>
    <head>
    <title>Login format</title>
    <style type="text/css">
        body {
            font-family: Meiryo;
            background-color:white;
        }

        .textback {
            padding: 0.5em 0;
            border-top: solid 3px #81e4af;
            border-bottom: solid 3px #81e4af;
        }

        .textbox {
            line-height: 50px;
            display: inline-block;
            text-align: right;
        }

        .formbox {
            padding: 10px;
            background-color: #b3e6cc;
            border: 2px #81e4af solid;
        }

        th {
            height: 20px;
            width: 20em;
            padding: 5px;
            background-color: #66cc99;
        }

        .attend {
	        background-color:#40bf80;
	        padding-left: 35px;
            padding-right: 35px;
            font-size: 20px;
            color:white;
        }

        .attend:hover {
            background-color: #C8C8DC;
        }

        .attend:active{
	        box-shadow: inset -2px -2px 3px rgba(255, 255, 255, .6),
                inset 2px 2px 3px rgba(0, 0, 0, .6);
        }
    </style>
</head>
<body>
    <h2 style="text-align:center"> Top Page </h2>
    <p class="textback" style="text-align:center">Click the "Begin" button.</p>

    <form class="formbox" style="text-align:center">
            <div>
                <input type="button" value="Begin" class="attend" onclick="location.href=`{% url 'attendance_book:teacher-input' %}`">
            </div>
    </form>

</body>
</html>

attendance_book/templates/attendance_book/student.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>hello world, student</p>
</body>
</html>

attendance_book/templates/attendance_book/teach_agg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Attendance Book (Aggregation)</title>
    <style>
        body {
            background-color: white;
        }

        .container {
            position: relative;
            border-radius: 2px;
            background-color: #f2f2f2;
            padding: 10px 20px 10px 20px;
        }

        #date {
            padding: 10px;
            background-color: #b3e6cc;
            border-radius: 2px;
        }

        th {
            width: 100px;
            height: 25px;
            padding: 5px;
            background-color: #66cc99;
            border-radius: 1px;
        }

        .attend-number, .attend-number-prev {
            display: none;
        }

        .attend-button {
            background-color: #40bf80;
            padding-left: 35px;
            padding-right: 35px;
            font-size: 20px;
            border-radius: 4px;
            color: white;
        }

        .attend-button:hover {
            background-color: rgba(200, 200, 220, 1) !important;
        }

        .attend-button:active {
            box-shadow: inset -2px -2px 3px rgba(255, 255, 255, .6), inset 2px 2px 3px rgba(0, 0, 0, .6);
        }

        .toolbar {
            overflow: auto;
            background-color: #26734d;
        }

        .toolbar_box {
            float: left;
            background-color: #66cc99;
            color: #333;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }

        .toolbar_box:hover {
            background-color: #333;
            color: #66cc99;
        }

        .dropdown {
            float: left;
            overflow: auto;
        }

        .dropdown .dropbtn {
            font-size: 14px;
            text-align: center;
            background-color: #66cc99;
            color: #333;
            padding: 14px 16px;
        }

        .dropbtn:hover {
            background-color: #333;
            color: #66cc99;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

        .dropdown-content a {
            float: none;
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
            text-align: left;
        }

        .dropdown-content a:hover {
            background-color: #ddd;
        }

        .dropdown:hover .dropdown-content {
            display: block;
        }

        #lightbox {
            background-color: rgba(0, 0, 0, 0.7);
            top: 0px;
            left: 0px;
            width: 100%;
            height: 100%;
            position: fixed;
            text-align: center;
            padding-top: 10%;
            z-index: 999;
            display: none;
        }
    </style>

    {% load static %}
    <script src="{% static 'attendance_book/jquery-3.6.0.min.js' %}"></script>
    <script>
        $(function () {
            $("#csv-output").attr("href", "{% url 'attendance_book:teacher-aggregation-download' %}" + location.search)

            if ($("#subject-input").val() != "None") {
                const at_json = {{ attendance_count | safe }};
                for (const key in at_json) {
                    $("#days-class-" + key).text(at_json[key]["days_class"]);
                    $("#days-absence-" + key).text(at_json[key]["days_absence"]);
                    $("#days-late-" + key).text(at_json[key]["days_late"]);
                    $("#days-early-" + key).text(at_json[key]["days_early"]);
                    $("#num-class-" + key).text(at_json[key]["num_class"]);
                    $("#num-absence-" + key).text(at_json[key]["num_absence"]);
                }
            }

            const subject_length = {{ subject_list | length }};
            for (let i=0; i<=subject_length; i++) {
                let css_selector = "#subject-" + String(i);
                $(css_selector).on("click", function(event){
                    let subject_name = $(css_selector).text();
                    $("#subject-input").val(subject_name);
                    $("#subject-input-hidden").val(i);
                });
            }

            $("#date").submit(function() {
                $("#lightbox").show();
            })
        });
    </script>
</head>
<body>
    {% if msg %}
    <p id="textback">{{msg}}</p>
    {% endif %}

    <div class="toolbar">
        <a class="toolbar_box" href="{% url 'attendance_book:teacher-input' %}">入力</a>
        <a class="toolbar_box" href="{% url 'attendance_book:teacher-aggregation' %}">集計</a>
        <div class="dropdown">
            <button class="dropbtn">▽科目</button>
            <div class="dropdown-content">
                <a id="subject-0">全体</a>
                {% for subject in subject_list %}
                <a id="subject-{{subject.id}}">{{ subject.name }}</a>
                {% endfor %}
            </div>
        </div>
        <a class="toolbar_box" id="csv-output">出力(CSV形式)</a>
    </div>

    <form class="date" id="date" action="{% url 'attendance_book:teacher-aggregation-post' %}" method="post">
        {% csrf_token %}
        <label for="subject-input">科目</label>
        <input id="subject-input" type="text" value="{{selected_subject}}" readonly>
        <input id="subject-input-hidden" type="hidden" name="subject" value="{{selected_subject.id}}">
        <label for="from-date-input">from</label>
        <input id="from-date-input" type="date" name="from-date" value="{{ from_d|date:'Y-m-d' }}">
        <label for="to-date-input">to</label>
        <input id="to-date-input" type="date" name="to-date" value="{{ to_d|date:'Y-m-d' }}">
        <input type="submit" name="aggregation" value="検索">
    </form>

    <table class="container">
        <tr>
            <th>番号</th>
            <th>名前</th>
            <th>授業日数</th>
            <th>欠席日数</th>
            <th>遅刻日数</th>
            <th>早退日数</th>
            <th>授業回数</th>
            <th>欠課数</th>
        </tr>
        {% for student in student_list %}
        <tr id="student-{{ student.class_num }}">
            <th>{{ student.class_num }}</th>
            <th>{{ student.person.name }}</th>
            <td id="days-class-{{ student.student_num }}"></td>
            <td id="days-absence-{{ student.student_num }}"></td>
            <td id="days-late-{{ student.student_num }}"></td>
            <td id="days-early-{{ student.student_num }}"></td>
            <td id="num-class-{{ student.student_num }}"></td>
            <td id="num-absence-{{ student.student_num }}"></td>
        </tr>
        {% endfor %}
    </table>

    <div id="lightbox">
        <img src="{% static 'attendance_book/load.gif' %}">
    </div>
</body>
</html>

attendance_book/templates/attendance_book/teach_agg_total.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Attendance Book (Aggregation)</title>
    <style>
        body {
            background-color: white;
        }

        .container {
            position: relative;
            border-radius: 2px;
            background-color: #f2f2f2;
            padding: 10px 20px 10px 20px;
        }

        #date {
            padding: 10px;
            background-color: #b3e6cc;
            border-radius: 2px;
        }

        th {
            width: 100px;
            height: 25px;
            padding: 5px;
            background-color: #66cc99;
            border-radius: 1px;
        }

        .attend-number, .attend-number-prev {
            display: none;
        }

        .attend-button {
            background-color: #40bf80;
            padding-left: 35px;
            padding-right: 35px;
            font-size: 20px;
            border-radius: 4px;
            color: white;
        }

        .attend-button:hover {
            background-color: rgba(200, 200, 220, 1) !important;
        }

        .attend-button:active {
            box-shadow: inset -2px -2px 3px rgba(255, 255, 255, .6), inset 2px 2px 3px rgba(0, 0, 0, .6);
        }

        .toolbar {
            overflow: auto;
            background-color: #26734d;
        }

        .toolbar_box {
            float: left;
            background-color: #66cc99;
            color: #333;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }

        .toolbar_box:hover {
            background-color: #333;
            color: #66cc99;
        }

        .dropdown {
            float: left;
            overflow: auto;
        }

        .dropdown .dropbtn {
            font-size: 14px;
            text-align: center;
            background-color: #66cc99;
            color: #333;
            padding: 14px 16px;
        }

        .dropbtn:hover {
            background-color: #333;
            color: #66cc99;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 160px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

        .dropdown-content a {
            float: none;
            color: black;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
            text-align: left;
        }

        .dropdown-content a:hover {
            background-color: #ddd;
        }

        .dropdown:hover .dropdown-content {
            display: block;
        }

        #lightbox {
            background-color: rgba(0, 0, 0, 0.7);
            top: 0px;
            left: 0px;
            width: 100%;
            height: 100%;
            position: fixed;
            text-align: center;
            padding-top: 10%;
            z-index: 999;
            display: none;
        }
    </style>

    {% load static %}
    <script src="{% static 'attendance_book/jquery-3.6.0.min.js' %}"></script>
    <script>
        $(function () {
            $("#csv-output").attr("href", "{% url 'attendance_book:teacher-aggregation-download' %}" + location.search)

            if ($("#subject-input").val() != "None") {
                const at_json = {{ attendance_count | safe }};
                for (const key in at_json) {
                    $("#days-class-" + key).text(at_json[key]["days_class"]);
                    $("#days-absence-" + key).text(at_json[key]["days_absence"]);
                    $("#days-late-" + key).text(at_json[key]["days_late"]);
                    $("#days-early-" + key).text(at_json[key]["days_early"]);
                    $("#num-class-" + key).text(at_json[key]["num_class"]);
                    $("#num-absence-" + key).text(at_json[key]["num_absence"]);
                }
            }

            const subject_length = {{ subject_list | length }};
            for (let i=0; i<=subject_length; i++) {
                let css_selector = "#subject-" + String(i);
                $(css_selector).on("click", function(event){
                    let subject_name = $(css_selector).text();
                    $("#subject-input").val(subject_name);
                    $("#subject-input-hidden").val(i);
                });
            }

            $("#date").submit(() => {
                $("#lightbox").show();
            })
        });
    </script>
</head>
<body>
    {% if msg %}
    <p id="textback">{{msg}}</p>
    {% endif %}

    <div class="toolbar">
        <a class="toolbar_box" href="{% url 'attendance_book:teacher-input' %}">入力</a>
        <a class="toolbar_box" href="{% url 'attendance_book:teacher-aggregation' %}">集計</a>
        <div class="dropdown">
            <button class="dropbtn">▽科目</button>
            <div class="dropdown-content">
                <a id="subject-0">全体</a>
                {% for subject in subject_list %}
                <a id="subject-{{subject.id}}">{{ subject.name }}</a>
                {% endfor %}
            </div>
        </div>
        <a class="toolbar_box" id="csv-output">出力(CSV形式)</a>
    </div>

    <form class="date" id="date" action="{% url 'attendance_book:teacher-aggregation-post' %}" method="post">
        {% csrf_token %}
        <label for="subject-input">科目</label>
        <input id="subject-input" type="text" value="全体" readonly>
        <input id="subject-input-hidden" type="hidden" name="subject" value="0">
        <label for="from-date-input">from</label>
        <input id="from-date-input" type="date" name="from-date" value="{{ from_d|date:'Y-m-d' }}">
        <label for="to-date-input">to</label>
        <input id="to-date-input" type="date" name="to-date" value="{{ to_d|date:'Y-m-d' }}">
        <input type="submit" name="aggregation" value="検索">
    </form>

    <table class="container">
        <tr>
            <th>番号</th>
            <th>名前</th>
            <th>授業日数</th>
            <th>欠席日数</th>
            <th>遅刻日数</th>
            <th>早退日数</th>
            <th>授業回数</th>
            <th>欠課数</th>
        </tr>
        {% for student in student_list %}
        <tr id="student-{{ student.class_num }}">
            <th>{{ student.class_num }}</th>
            <th>{{ student.person.name }}</th>
            <td id="days-class-{{ student.student_num }}"></td>
            <td id="days-absence-{{ student.student_num }}"></td>
            <td id="days-late-{{ student.student_num }}"></td>
            <td id="days-early-{{ student.student_num }}"></td>
            <td id="num-class-{{ student.student_num }}"></td>
            <td id="num-absence-{{ student.student_num }}"></td>
        </tr>
        {% endfor %}
    </table>

    <div id="lightbox">
        <img src="{% static 'attendance_book/load.gif' %}">
    </div>
</body>
</html>